import '@/lib/ui/css/main.css';

import { Inter } from 'next/font/google';

import { Header, PageContainer } from './components';
import { FULL_NAME } from './config';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: FULL_NAME,
  // TODO: add a meaningful description
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <PageContainer>{children}</PageContainer>
      </body>
    </html>
  );
}
